suorganizer/blogs/urls.py
from django.urls import path
from .views import (
    PostList,
    PostDetail,
    PostCreate,
    PostUpdate,
    PostDelete,
    PostArchiveYear,
    PostArchiveMonth,
)

urlpatterns = [
    path('', PostList.as_view(), name='blogs_posts_list'),
    path('<int:year>/<int:month>/<slug:slug>/', PostDetail.as_view(), name='blogs_post_detail'),
    path('create/', PostCreate.as_view(), name='blogs_post_create'),
    path('<int:year>/<int:month>/<slug:slug>/update/', PostUpdate.as_view(), name='blogs_post_update'),
    path('<int:year>/<int:month>/<slug:slug>/delete/', PostDelete.as_view(), name='blogs_post_delete'),
    path('<int:year>/', PostArchiveYear.as_view(), name='blogs_post_archive_year'),
    path('<int:year>/<int:month>/', PostArchiveMonth.as_view(), name='blogs_post_archive_month'),
]

suorganizer/suorganizer/urls.py
import os
from blogs import urls as blog_urls
from contacts import urls as contact_urls
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view
)

from .sitemaps import sitemaps as sitemaps_dict
from organizers.urls import startup as start_urls
from organizers.urls import tag as tag_urls
from users import urls as user_urls
from blogs.feeds import AtomPostFeed, Rss2PostFeed
from organizers.feeds import AtomStartupFeed, Rss2StartupFeed

admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'
# Url configuration for new feeds
sitenews = [
    path('atom/', AtomPostFeed(), name='blogs_atom_feed'),
    path('rss/', Rss2PostFeed(), name='blogs_rss_feed'),
]
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include(blog_urls)),
    path('contact/', include(contact_urls)),
    path('startup/', include(start_urls)),
    path('tag/', include(tag_urls)),
    path('about/', TemplateView.as_view(template_name='site/about.html'), name='about_site'),
    path('mission/', TemplateView.as_view(template_name='site/mission.html'), name='site_mission'),
    path('how/', TemplateView.as_view(template_name='site/work.html'), name='site_work'),
    path('', RedirectView.as_view(
        pattern_name='blogs_posts_list',
        permanent=False
    )),
    path('users/', include(user_urls,
                           namespace='dj-auth')),
    path('sitenews/', include(sitenews)),
    path('<slug:startup_slug>/atom/', AtomStartupFeed(), name='organizers_startup_atom_feed'),
    path('<slug:startup_slug>/rss/', Rss2StartupFeed(), name='organizers_startup_rss_feed'),
    # The index view is a higher level overview of the sitemaps
    # for each section of the application.
    path('sitemap.xml', site_index_view, {'sitemaps': sitemaps_dict},
         name='sitemaps'),
    path('sitemap-<section>.xml', sitemap_view, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

suorganizer/organizers/models.py
from datetime import date
from urllib.parse import urlparse

from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property


class TagManager(models.Manager):
    """
    Custom manager class for Tag model.
    """

    def get_by_natural_key(self, slug):
        """
        Method to use natural key in
        deserialization.
        :param slug:
        :return:
        """
        return self.get(
            slug=slug
        )


class Tag(models.Model):
    name = models.CharField(max_length=31,
                            unique=True)
    slug = models.SlugField(unique=True,
                            max_length=31,
                            help_text='A label for URL Config')

    def __str__(self):
        # to capitalise the first Character
        return 'Tag with name {}' \
            .format(self.name.title())

    objects = TagManager()

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('organizers_tag_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizers_tag_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizers_tag_delete', kwargs={'slug': self.slug})

    @cached_property
    def published_posts(self):
        """
        Method to return a queryset to
        filter for published posts only.
        The method helps with showing future
        articles only for those users with
        having the corresponding permission,
        the template
        The resulting queryset is changed
        into a tuple, as tuple has a smaller
        memory footprint.
        :return:
        """
        return tuple(self.blog_posts.filter(
            pub_date__lt=date.today()
        ))

    def natural_key(self):
        """
        Method to create human friendly
        serialized data
        This method must return a tuple
        :return:
        """
        return (
            self.slug
        )


class StartupManager(models.Model):
    """
    Custom manager class for Startup model
    """

    def get_by_natural_key(self, slug):
        """
        Method to be used in deserialization
        of startup objects
        :param slug:
        :return:
        """
        return self.get(slug=slug)


class Startup(models.Model):
    name = models.CharField(max_length=31,
                            db_index=True)
    slug = models.SlugField(max_length=31,
                            unique=True,
                            help_text='A label for URL Config')
    description = models.TextField()
    founded_date = models.DateField('Date Founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return 'Startup with Title {}' \
            .format(self.name.title())

    objects = StartupManager()

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def get_absolute_url(self):
        return reverse('organizers_startup_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizers_startup_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizers_startup_delete', kwargs={'slug': self.slug})

    def get_newslink_create_url(self):
        return reverse(
            'organizers_newslink_create',
            kwargs={
                'startup_slug': self.slug
            })

    def natural_key(self):
        """
        Method used to create human friendly
        serialized data
        This method must return a tuple, hence
        the parenthesis
        :return:
        """
        return (self.slug)

    @cached_property
    def published_posts(self):
        """
        Method to return a queryset to
        filter for published posts only.
        The method helps with showing future
        articles only for those users with
        having the corresponding permission,
        the template
        The resulting queryset is changed
        into a tuple, as tuple has a smaller
        memory footprint.
        :return:
        """
        return tuple(self.blog_posts.filter(
            pub_date__lt=date.today()
        ))

    def get_feed_atom_url(self):
        """
        Method to return the reverse of
        organizers_startup_atom_feed
        for startup
        """
        return reverse(
            'organizers_startup_atom_feed',
            kwargs={'startup_slug': self.slug}
        )

    def get_feed_rss_url(self):
        """
        Method to return the reverse of
        organizers_startup_rss_feed
        for startup.
        """
        return reverse(
            'organizers_startup_rss_feed',
            kwargs={'startup_slug': self.slug}
        )

class NewsLinkManager(models.Model):
    """
    Custom manager class for NewsLink
    """

    def get_by_natural_key(self, startup_slug, slug):
        """
        Method to be used for deserialization of data
        :param startup_slug:
        :param slug:
        :return:
        """
        return self.get(
            startup_slug=self.startup_slug,
            slug=self.slug
        )


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('Date Published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup,
                                on_delete=models.CASCADE)
    slug = models.SlugField(max_length=63)

    def __str__(self):
        return 'NewsLink for startup {}: with title {}'.format(
            self.startup,
            self.title
        )

    objects = NewsLinkManager()

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together = ('slug', 'startup')

    def get_absolute_url(self):
        return reverse('organizers_startup_detail', kwargs={
            'slug': self.startup.slug
        })

    def get_update_url(self):
        return reverse('organizers_newslink_update',
                       kwargs={
                           'startup_slug': self.startup.slug,
                           'newslink_slug': self.slug
                       })

    def get_delete_url(self):
        return reverse('organizers_newslink_delete',
                       kwargs={
                           'startup_slug': self.startup.slug,
                           'newslink_slug': self.slug
                       })

    def natural_key(self):
        """
        Method used to serialize
        Newslink object in a human friendly
        way.
        :return:
        """
        return (
            self.startup.natural_key(),
            self.slug
        )

    natural_key.dependencies = [
        'organizers.startup',
        'organizers.tag',
        'users.user'
    ]

    def description(self):
        """
        Method to return a string
        containing date and url
        of a newslink
        """
        return (
            'Written on '
            '{0: %A, %B} {0.day}, {0:%Y}; '
            'hosted at {1}'.format(
                self.pub_date,
                urlparse(self.link).netloc
            )
        )

suorganizer/organizers/forms.py
"""
A module containing form classes
for organizers app
"""
from django import forms
from django.forms import HiddenInput, SelectDateWidget

from .mixins import SlugCleanMixin
from .models import (
    Tag,
    NewsLink,
    Startup
)


class TagForm(SlugCleanMixin,
              forms.ModelForm):
    """Form class for tag"""

    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()


class NewsLinkForm(
    SlugCleanMixin,
    forms.ModelForm):
    """Form class for newslink"""
    pub_date = forms.DateField(label='Date Published', initial='yyyy-mm-dd')
    class Meta:
        model = NewsLink
        fields = '__all__'
        widgets = {'startup': HiddenInput()}


class StartupForm(SlugCleanMixin,
                  forms.ModelForm):
    """Form class for startup"""
    founded_date = forms.DateField(label='Date Founded', initial='yyyy-mm-dd')

    class Meta:
        model = Startup
        fields = '__all__'

suorganizer/organizers/views.py
"""
view module for organizers app
"""
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
)

from .forms import (
    TagForm,
    StartupForm,
    NewsLinkForm
)
from .mixins import (
    PageLinksMixin,
    StartupContextMixin,
    NewsLinkGetObjectMixin,
)
from .models import Tag, Startup, NewsLink


class TagList(PageLinksMixin, ListView):
    """Tag list view"""
    template_name = 'tag/tag_list.html'
    paginate_by = 5
    model = Tag


class TagDetail(DetailView):
    """Tag detail view"""
    template_name = 'tag/tag_detail.html'
    queryset = Tag.objects. \
        prefetch_related('startup_set')


class TagCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Tag create view"""
    form_class = TagForm
    template_name = 'tag/tag_form.html'
    permission_required = 'organizers.change_tag'


class TagUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Tag update view"""
    form_class = TagForm
    model = Tag
    template_name = 'tag/tag_form_update.html'
    permission_required = 'organizers.change_tag'


class TagDelete(LoginRequiredMixin, DeleteView):
    """Tag delete view"""
    template_name = 'tag/tag_confirm_delete.html'
    model = Tag
    success_url = reverse_lazy('organizers_tag_list')


class StartupList(PageLinksMixin, ListView):
    """Startup list view"""
    template_name = 'startup/startup_list.html'
    paginate_by = 5
    page_kwarg = 'page'
    model = Startup


class StartupDetail(DetailView):
    """Startup detail view"""
    template_name = 'startup/startup_detail.html'
    queryset = Startup.objects. \
        prefetch_related('tags') \
        .prefetch_related('newslink_set')


class StartupCreate(LoginRequiredMixin, CreateView):
    """Startup create view"""
    form_class = StartupForm
    template_name = 'startup/startup_form.html'


class StartupUpdate(LoginRequiredMixin, UpdateView):
    """startup update view"""
    form_class = StartupForm
    model = Startup
    template_name = 'startup/startup_form_update.html'


class StartupDelete(LoginRequiredMixin, DeleteView):
    """Startup delete view"""
    model = Startup
    template_name = 'startup/startup_confirm_delete.html'
    success_url = reverse_lazy('organizers_startup_list')


class NewsLinkCreate(LoginRequiredMixin, NewsLinkGetObjectMixin,
                     StartupContextMixin,
                     CreateView):
    """Newslink create view"""
    form_class = NewsLinkForm
    template_name = 'newslink/newslink_form.html'
    # Django by default will use get_absolute_url
    # to redirect to the newly created object detail view
    # however in our case newslink doesn't have that view
    success_url = reverse_lazy('organizers_startup_list')
    model = NewsLink

    # noinspection PyAttributeOutsideInit
    def get_initial(self):
        """
        Overriding method to add startup to
        the initial.
        Initial is then passed to the form as initial parameters
        :return:
        """
        startup_slug = self.kwargs.get(
            self.startup_slug_url_kwarg
        )
        self.startup = get_object_or_404(Startup,
                                         slug__iexact=startup_slug)
        initial = {
            self.startup_context_object_name: self.startup,
        }
        initial.update(self.initial)
        return initial


class NewsLinkUpdate(
    LoginRequiredMixin,
    StartupContextMixin,
    NewsLinkGetObjectMixin,
    UpdateView):
    """Newslink update view"""
    form_class = NewsLinkForm
    model = NewsLink
    template_name = 'newslink/newslink_form_update.html'
    # override the slug_url_kwarg so that the view knows to accept
    # newslink_slug instead of just slug
    slug_url_kwarg = 'newslink_slug'


class NewsLinkDelete(
    LoginRequiredMixin,
    StartupContextMixin,
    NewsLinkGetObjectMixin,
    DeleteView):
    """Newslink Delete view"""
    template_name = 'newslink/newslink_confirm_delete.html'
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'

    def get_success_url(self):
        """
        Redirect to the startup that the newslink was associated with,
        when the newslink is deleted.
        :return:
        """
        return (self.object.startup.
                get_absolute_url())

suorganizer/organizers/templates/startup/startup_confirm_delete.html
{% extends 'organizer/base_organizer.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Delete Startup
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% delete_form startup.get_delete_url 'Delete Startup' startup %}
        </div>
    <div class="col-md-4">
    <p>
        <a href="{{ request.META.HTTP_REFERER}}">Go Back</a>
    </p>
        </div>
    </div>
{% endblock content %}

suorganizer/organizers/templates/startup/startup_detail.html
{% extends 'organizer/base_organizer.html' %} {% block title %} {{ block.super }} - {{ startup.name }} {% endblock title %} {% block content %}
{% load obfuscate_email %}
{% load partial_post_list %}
<article>
    <h2 class="text-center text-info">{{ startup.name }}</h2>
    <div>
        <dl class="row">
            <dt class="col-sm-3">Date Founded</dt>
            <dd class="col-sm-9">{{ startup.founded_date|date:"F jS, Y" }}</dd>
            <dt class="col-sm-3">Website</dt>
            <dd class="col-sm-9">{{ startup.website|urlize }}</dd>
            <dt class="col-sm-3">Contact</dt>
            <dd class="col-sm-9">{{ startup.contact|obfuscate }}</dd>
            {% with tag_list=startup.tags.all %}
            <dt class="col-sm-3">Tag{{ tag_list|pluralize }}</dt>
            <dd class="col-sm-9">
                {% for tag in tag_list %}
                <a href="{{ tag.get_absolute_url }}">
                    {{ tag.name|title }},
                </a>
                {% endfor %}
            </dd>
            {% endwith %}
            <dt class="col-sm-3">Feeds</dt>
            <dd class="col-sm-9">
                <a href="{{ startup.get_feed_atom_url }}">Atom, </a>
                <a href="{{ startup.get_feed_rss_url }}">RSS</a>
            </dd>
        </dl>
    </div>
    <div class="description">
        {{ startup.description|linebreaks }}
    </div>
    <div class="d-flex justify-content-start">
        <p>
            {% if perms.organizers.change_startup %}
            <a class="text-warning" href="{{ startup.get_update_url }}" title="Edit"><span
                    class="material-icons">edit</span></a>
            {% endif %}
        </p>
        <p>
            {% if perms.organizers.delete_startup %}
            <a class="text-danger" href="{{ startup.get_delete_url }}" title="Delete">
                <span class="material-icons">delete_forever</span></a>
            {% endif %}
        </p>
    </div>
    {% if startup.newslink_set.all %}
    <section>
        <h3 class="text-center">Recent News</h3>
        <div>
            <table class="table table-dark bg-transparent">
                <thead>
                <tr>
                    <th scope="col">Title</th>
                    {% if perms.organizers.change_newslink %}
                    <th scope="col">Update</th>
                    {% endif %}
                    {% if perms.organizers.delete_newslink %}
                    <th scope="col">Delete</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for newslink in startup.newslink_set.all %}
                <tr>
                    <td><a href="{{ newslink.get_absolute_url }}">
                        {{ newslink.title|title }}</a>
                    </td>
                    <td>
                        {% if perms.organizers.change_newslink %}
                        <a class="text-warning" href="{{ newslink.get_update_url }}" title="Edit Link"><span
                                class="material-icons">edit</span></a>
                        {% endif %}
                    </td>
                    <td>
                        {% if perms.organizers.delete_newslink %}
                        <a class="text-danger" href="{{ newslink.get_delete_url }}" title="Delete Link"><span
                                class="material-icons">delete_forever</span></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
    {% endif %}
    <section class="add_post_button">
    {% if perms.organizers.add_newslink %}
    <a class="text-info btn btn-outline-info btn-lg btn-block" href="{{ startup.get_newslink_create_url }}">Add Article</a>
    {% endif %}
    </section>
        {% format_post_list startup %}
</article>
<p>
    <a href="{{ request.META.HTTP_REFERER}}">Go Back</a>
</p>
{% endblock content %}

suorganizer/organizers/templates/startup/startup_form.html
{% extends 'organizer/base_organizer.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Create Startup
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% url 'organizers_startup_create' as form_url %}
        {% form form_url 'Create Startup' 'post' button_classes='btn btn-outline-success btn-lg btn-block' %}
        </div>
    </div>
{% endblock content %}

suorganizer/organizers/templates/startup/startup_form_update.html
{% extends 'organizer/base_organizer.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Update Startup
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% form startup.get_update_url 'Update Startup' 'post' button_classes='btn btn-outline-warning btn-lg btn-block' %}
        </div>
    </div>
{% endblock content %}

suorganizer/organizers/templates/startup/startup_list.html
{% extends 'organizer/base_organizer.html' %}
{% block title %}
{{ block.super }} - Startups
{% endblock title %}
{% block org_content %}
 <h2>Startup List</h2>
    <ul>
        {% for startup in page_obj %}
        <li>
            <a href="{{ startup.get_absolute_url }}">
                {{ startup.name }}
            </a>
        </li>
        {% empty %}
        <li><em>No Startups Available</em></li>
        {% endfor %}
</ul>
{% endblock org_content %}
{% block create_button %}
{% if perms.organizers.add_startup %}
    <a class="text-info btn btn-outline-info btn-lg btn-block" href="{% url 'organizers_startup_create' %}" title="Add Tag">Add a Startup</a>
{% endif %}
{% endblock create_button %}