suorganizer/blogs/urls.py
from django.urls import path
from .views import (
    PostList,
    PostDetail,
    PostCreate,
    PostUpdate,
    PostDelete,
    PostArchiveYear,
    PostArchiveMonth,
)

urlpatterns = [
    path('', PostList.as_view(), name='blogs_posts_list'),
    path('<int:year>/<int:month>/<slug:slug>/', PostDetail.as_view(), name='blogs_post_detail'),
    path('create/', PostCreate.as_view(), name='blogs_post_create'),
    path('<int:year>/<int:month>/<slug:slug>/update/', PostUpdate.as_view(), name='blogs_post_update'),
    path('<int:year>/<int:month>/<slug:slug>/delete/', PostDelete.as_view(), name='blogs_post_delete'),
    path('<int:year>/', PostArchiveYear.as_view(), name='blogs_post_archive_year'),
    path('<int:year>/<int:month>/', PostArchiveMonth.as_view(), name='blogs_post_archive_month'),
]

suorganizer/suorganizer/urls.py
import os
from blogs import urls as blog_urls
from contacts import urls as contact_urls
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view
)

from .sitemaps import sitemaps as sitemaps_dict
from organizers.urls import startup as start_urls
from organizers.urls import tag as tag_urls
from users import urls as user_urls
from blogs.feeds import AtomPostFeed, Rss2PostFeed
from organizers.feeds import AtomStartupFeed, Rss2StartupFeed

admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'
# Url configuration for new feeds
sitenews = [
    path('atom/', AtomPostFeed(), name='blogs_atom_feed'),
    path('rss/', Rss2PostFeed(), name='blogs_rss_feed'),
]
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include(blog_urls)),
    path('contact/', include(contact_urls)),
    path('startup/', include(start_urls)),
    path('tag/', include(tag_urls)),
    path('about/', TemplateView.as_view(template_name='site/about.html'), name='about_site'),
    path('mission/', TemplateView.as_view(template_name='site/mission.html'), name='site_mission'),
    path('how/', TemplateView.as_view(template_name='site/work.html'), name='site_work'),
    path('', RedirectView.as_view(
        pattern_name='blogs_posts_list',
        permanent=False
    )),
    path('users/', include(user_urls,
                           namespace='dj-auth')),
    path('sitenews/', include(sitenews)),
    path('<slug:startup_slug>/atom/', AtomStartupFeed(), name='organizers_startup_atom_feed'),
    path('<slug:startup_slug>/rss/', Rss2StartupFeed(), name='organizers_startup_rss_feed'),
    # The index view is a higher level overview of the sitemaps
    # for each section of the application.
    path('sitemap.xml', site_index_view, {'sitemaps': sitemaps_dict},
         name='sitemaps'),
    path('sitemap-<section>.xml', sitemap_view, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

suorganizer/users/urls.py
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

from .views import (DisableAccount, CreateAccount,
                    ActivateAccount, ResendActivationEmail,
                    ProfileDetail, ProfileUpdate, PublicProfileDetail)

app_name = 'dj-auth'

password_url = [
    # We are adding this pattern to ensure that
    # /user/password/ pattern is resolved.
    # This is good practice.
    path('',
         RedirectView.as_view(
             pattern_name='dj-auth:pw_reset_start',
             permanent=False
         )),
    path('change/',
         auth_views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url=reverse_lazy('dj-auth:pw_change_done')
         ), name='pw_change'),
    path('change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'
         ), name='pw_change_done'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.txt',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('dj-auth:pw_reset_sent')
    ), name='pw_reset_start'),
    path('reset/sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_sent.html'
    ), name='pw_reset_sent'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('dj-auth:pw_reset_complete')
    ), name='pw_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',
        extra_context={'form': 'AuthenticationForm'}
    ), name='pw_reset_complete')

]

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'
    )
         , name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logged_out.html',
        extra_context={
            'form': AuthenticationForm

        }
    )
         , name='logout'),
    path('password/', include(password_url)),
    path('disable/', DisableAccount.as_view(), name='disable'),
    path('create/', CreateAccount.as_view(), name='create'),
    path('create/done/', TemplateView.as_view(
        template_name='users/user_create_done.html'),
         name='create_done'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(),
         name='activate'),
    path('activate/resend/', ResendActivationEmail.as_view(),
         name='resend_activation'),
    path('profile/',
         ProfileDetail.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdate.as_view(),
         name='profile_update'),
    path('<slug:slug>/', PublicProfileDetail.as_view(),
         name='public_profile'),
    # Just like the above we have to add this path
    # as currently /user/activate/ doesn't resolve
    path('activate/',
         RedirectView.as_view(
             pattern_name=(
                 'dj-auth:resend_activation'
             ),
             permanent=False
         )),
    path('', RedirectView.as_view(
        pattern_name='dj-auth:login',
        permanent=False
    ), ),
]

suorganizer/users/forms.py
import logging
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import \
    UserCreationForm as BaseUserCreationForm, \
    UserChangeForm as BaseUserChangeForm
from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .mixins import ActivationMailFormMixin
from .models import Profile

logger = logging.getLogger(__name__)


class UserCreationForm(ActivationMailFormMixin,
                       BaseUserCreationForm):
    """
    Form class for user creation
    """
    mail_validation_error = (
        'User created. Could not send activation '
        'email. Please try again later. (Sorry!)'
    )
    # Name field added to the form only.
    # The value from this field will be used
    # to create profile for the user
    name = forms.CharField(
        max_length=255,
        help_text=(
            'The name displayed on your '
            'public profile.'
        )
    )

    def save(self, **kwargs):
        """
        Overriding save method with multiple steps
        Passing it **kwargs required by send_mail()
        We then get the user and check if it already
        has a primary key in the database, if it has
        it means the user data is already in the database
        and we don't need to send an account activation
        email, if the primary key is not in the database
        we then send the account activation email.
        :param kwargs:
        :return:
        """
        user = super().save(commit=False)
        if not user.pk:
            user.is_active = False
            send_mail = True
        else:
            send_mail = False
        # After knowing to send email or not we need to save
        # the user to the database.
        user.save()
        # To save any many-to-many relations we call save_m2m()
        self.save_m2m
        # create or update the user profile
        Profile.objects.update_or_create(
            user=user,
            defaults={
                'name': self.cleaned_data['name'],
                'slug': slugify(self.cleaned_data['name'])
            }
        )
        if send_mail:
            self.send_mail(user, **kwargs)
        return user

    def clean_name(self):
        """
        Method to check that name is
        not in the set of disallowed
        names. If name of user is
        login it means their profile will
        be accessible with url users/login/
        which is our login url.
        :return:
        """
        name = self.cleaned_data['name']
        disallowed = (
            'activate',
            'create',
            'disable',
            'login',
            'logout',
            'password',
            'profile',
        )
        if name in disallowed:
            raise ValidationError(
                'A user with that username'
                'already exists.'
            )
        return name

    class Meta(BaseUserCreationForm.Meta):
        """
        To properly restructure UserCreationForm to use
        the fields in BaseUserCreationForm, we need to
        change the Meta class where the ModelForm
        behaviour is defined.
        This meta class therefore inherits the Meta class
        in BaseUserCreationForm, overriding the model
        with get_user_model() and adding the email
        form to the field.
        """
        model = get_user_model()
        fields = ['email', 'email']


class ResendActivationEmailForm(ActivationMailFormMixin,
                                forms.Form):
    """
    Form class for sending activation link to user
    whose previous link has expired.
    """

    email = forms.EmailField()

    mail_validation_error = (
        'Could not re-send activation email.'
        'Please try again later.'
    )

    def save(self, **kwargs):
        User = get_user_model()
        try:
            user = User.objects.get(
                email=self.cleaned_data['email']
            )
        except:
            logger.warning(
                'Resend Activation: No user with'
                'email: {} .'.format(self.cleaned_data['email'])
            )
            return None
        self.send_mail(user=user, **kwargs)
        return user


class UserChangeForm(BaseUserChangeForm):
    """
    For UserAdmin
    """

    class Meta(BaseUserChangeForm.Meta):
        model = get_user_model()

suorganizer/users/views.py
"""
View Module for Users app
"""
from django.utils.decorators import method_decorator
from django.conf import settings
from django.contrib.auth import get_user, logout, get_user_model
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
)
from django.contrib.auth.tokens import \
    default_token_generator as token_generator
from django.contrib.messages import error, success
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import DetailView, UpdateView

from .forms import UserCreationForm, ResendActivationEmailForm
from .mixins import MailContextViewMixin, ProfileGetObjectMixin
from .models import Profile


class DisableAccount(LoginRequiredMixin, View):
    """
    A class to define view to disable user account
    """
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = (
        'users/user_confirm_delete.html'
    )

    def get(self, request):
        """GET Method"""
        return TemplateResponse(request, self.template_name)

    def post(self, request):
        """
        Disables the user account once user has confirmed it
        :param request:
        :return:
        """
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout(request)
        return redirect(self.success_url)


class CreateAccount(MailContextViewMixin, View):
    """
    A class view to create a user
    """
    form_class = UserCreationForm
    success_url = reverse_lazy('dj-auth:create_done')
    template_name = 'users/user_create.html'

    def get(self, request):
        """
        Method to show form
        :return:
        """
        return TemplateResponse(
            request,
            self.template_name,
            {'form': self.form_class()}
        )

    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def post(self, request):
        """
        Post method dealing with form once
        returned by the user
        :param request:
        :return:
        """
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            # we are using get_save_kwargs to get data from
            # request and pass it on to the save() that will
            # pass it to the send_mail method
            bound_form.save(**self.get_save_kwargs(request))
            # using mail_sent from mixin we check if email
            # has been sent
            if bound_form.mail_sent:
                return redirect(self.success_url)
            else:
                errs = (
                    bound_form.non_field_errors()
                )
                # Adding errors to the messages
                for err in errs:
                    error(request, err)
                return redirect(
                    'dj-auth:resend_activation'
                )
        return TemplateResponse(request,
                                self.template_name,
                                {'form': bound_form})


class ActivateAccount(View):
    """
    View for dealing with activating
    account
    """
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'users/user_active.html'

    @never_cache
    def get(self, request, uidb64, token):
        """
        Get method to check user using uidb64
        check that token is valid
        :param request:
        :param uidb64:
        :param token:
        :return:
        """
        user = get_user_model()
        try:
            uid = force_str(
                urlsafe_base64_decode(uidb64)
            )
            user = user.objects.get(pk=uid)
        except (TypeError, ValueError,
                OverflowError, user.DoesNotExist):
            user = None
        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            success(
                request,
                'User Activated!'
                'You may login.'
            )
            return redirect(self.success_url)
        else:
            return TemplateResponse(request,
                                    self.template_name)


class ResendActivationEmail(MailContextViewMixin, View):
    """
    View class to resend activation email
    """
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'users/resend_activation.html'

    def get(self, request):
        """
        Get method to send the form
        :param request:
        :return:
        """
        return TemplateResponse(
            request, self.template_name,
            {'form': self.form_class()}
        )

    def post(self, request):
        """
        Post method for the view
        :param request:
        :return:
        """
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(
                **self.get_save_kwargs(request)
            )
            if (user is not None
                    and not bound_form.mail_sent):
                errs = (
                    bound_form.non_field_errors()
                )
                # Errors are displayed in messages
                # and then removed from the form
                for err in errs:
                    error(request, err)
                if errs:
                    bound_form.errors.pop(
                        '__all__'
                    )
                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form': bound_form}
                )
        success(
            request,
            'Activation email sent'
        )
        return redirect(self.success_url)


class ProfileDetail(LoginRequiredMixin,
                    ProfileGetObjectMixin, DetailView):
    """
    A view to show the profile of a logged in user.
    """
    model = Profile


class ProfileUpdate(LoginRequiredMixin,
                    ProfileGetObjectMixin, UpdateView):
    """
    A view to update user profile
    """
    fields = ('about',)
    model = Profile
    template_name = 'users/profile_form_update.html'


class PublicProfileDetail(DetailView):
    """
    A view to show profile to other users
    """
    model = Profile

suorganizer/users/templates/users/logged_out.html
{% extends 'users/base_user.html' %}
{% block title %}
{{ block.super }} - Logged Out
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-5">
        <p class="text-info">You have successfully logged out.</p>
        {% include 'users/login_form.html' with login_button='Log Back In' %}
    </div>
</div>
{% endblock %}

suorganizer/users/templates/users/login.html
{% extends 'users/base_user.html' %}
{% load static %}
{% block title %}
{{ block.super }} - Login
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-5">
        <a href="{% url 'dj-auth:create' %}">Register New Account</a>
        <hr>
        {% include 'users/login_form.html' %}
        <hr>
        <a href="{% url 'dj-auth:pw_reset_start' %}">Forgotten your Password?</a>
        <a href="{% url 'dj-auth:resend_activation' %}">Lost Activation Email?</a>
    </div>
    <div class="col-md-7">
        <img class="rounded img-thumbnail img-fluid"
             src="{% static  'images/christian-wiediger-WkfDrhxDMC8-unsplash.jpg' %}">
    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/password_change_done.html
{% extends 'users/base_user.html' %}
{% block title %}
{{ block.super }} - Change Password
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <p class="text-success">Password successfully changed.</p>

    </div>
</div>
{% endblock %}

suorganizer/users/templates/users/password_change_form.html
{% extends 'users/base_user.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Change Password
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% url 'dj-auth:pw_change' as form_url %}
        {% form form_url 'Change Password' 'post' button_classes='btn btn-outline-warning btn-lg btn-block' %}
    </div>
</div>
{% endblock %}

suorganizer/users/templates/users/password_reset_complete.html
{% extends 'users/base_user.html' %}
{% block title %}
{{ block.super }} - Password Reset
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <p class="text-success">Your Password has been reset.</p>
        <p class="text-success">Please Login using your new Password</p>
    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/password_reset_confirm.html
{% extends 'users/base_user.html' %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Password Reset
{% endblock title %}
{% block content %}
<div class="row">
    <div class="class=col-md-5">
        {% if validlink %}
        <p class="text-info">Please enter a new password below</p>
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-primary btn-lg btn-block" type="submit">Save New Password</button>
        </form>
        {% else %}
        <p class="text-warning">This reset link is no longer valid.</p>
        <p class="text-warning">Please request a new link <a href="{% url 'dj-auth:pw_reset_start' %}">here</a>.</p>
        {% endif %}
    </div>
    <div class="col-md-7">
        <img class="rounded img-thumbnail"
             src="{{ STATICFILES_DIRS }}/static/images/christian-wiediger-WkfDrhxDMC8-unsplash.jpg"/>
    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/password_reset_form.html
{% extends 'users/base_user.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Reset Password
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% url 'dj-auth:pw_reset_start' as form_url %}
        {% form form_url 'Send me Reset Instructions' 'post' button_classes='btn btn-outline-warning btn-lg btn-block' %}
    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/password_reset_sent.html
{% extends 'users/base_user.html' %}
{% block title %}
{{ block.super }} - Password Reset Sent
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <p class="text-success">Password reset email sent.</p>
        <p class="text-success">Please check your inbox and spam box.</p>
    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/profile_form_update.html
{% extends 'users/base_user.html' %}
{% load display_form  %}
{% block title %}
{{ block.super }} - Update Profile
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-7">
        {% form profile.get_update_url 'Update Profile' 'post' button_classes='btn btn-outline-success btn-lg btn-block' %}
    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/resend_activation.html
{% extends 'users/base_user.html' %}
{% load static %}
{% block title %}
{{ block.super }} - Resend Activation E-Mail
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <form action="{% url 'dj-auth:resend_activation' %}" method="post">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {{ form|crispy }}
            <button class="btn btn-outline-success btn-lg btn-block" type="submit">Resend Activation Email</button>
        </form>

    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/user_activate.html
{% extends 'users/base_user.html' %}
{% block title %}
{{ block.super }} - Account Activation Failed
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <p class="text-danger">
            This activation link is no longer valid.
        </p>
    </div>
</div>
{% endblock %}

suorganizer/users/templates/users/user_confirm_delete.html
{% extends 'users/base_user.html' %}
{% load static %}
{% load display_form %}
{% block title %}
{{ block.super }} - Disable Account
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <p class="text-warning">The changes that you are making will not be undone.</p>
        {% url 'dj-auth:disable' as form_url %}
        {% delete_form form_url 'Disable Account' user %}
    </div>
    <div class="col-md-4">
    <p>
        <a href="{{ request.META.HTTP_REFERER}}">Go Back</a>
    </p>
        </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/user_create.html
{% extends 'users/base_user.html' %}
{% load static %}
{% block title %}
{{ block.super }} - Create Account
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <form action="{% url 'dj-auth:create' %}" method="post">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {{ form|crispy }}
            <button class="btn btn-outline-success btn-lg btn-block" type="submit">Create New Account</button>
        </form>

    </div>
</div>
{% endblock content %}

suorganizer/users/templates/users/user_create_done.html
{% extends 'users/base_user.html' %}
{% block title %}
{{ block.super }} - Account Created
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <p class="text-success">
            Your Account has been created!
        </p>
        <p class="text-success">
            Please check your email for the activation link.
        </p>
    </div>
</div>
{% endblock %}