suorganizer/blogs/urls.py
from django.urls import path
from .views import (
    PostList,
    PostDetail,
    PostCreate,
    PostUpdate,
    PostDelete,
    PostArchiveYear,
    PostArchiveMonth,
)

urlpatterns = [
    path('', PostList.as_view(), name='blogs_posts_list'),
    path('<int:year>/<int:month>/<slug:slug>/', PostDetail.as_view(), name='blogs_post_detail'),
    path('create/', PostCreate.as_view(), name='blogs_post_create'),
    path('<int:year>/<int:month>/<slug:slug>/update/', PostUpdate.as_view(), name='blogs_post_update'),
    path('<int:year>/<int:month>/<slug:slug>/delete/', PostDelete.as_view(), name='blogs_post_delete'),
    path('<int:year>/', PostArchiveYear.as_view(), name='blogs_post_archive_year'),
    path('<int:year>/<int:month>/', PostArchiveMonth.as_view(), name='blogs_post_archive_month'),
]

suorganizer/suorganizer/urls.py
import os
from blogs import urls as blog_urls
from contacts import urls as contact_urls
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view
)

from .sitemaps import sitemaps as sitemaps_dict
from organizers.urls import startup as start_urls
from organizers.urls import tag as tag_urls
from users import urls as user_urls
from blogs.feeds import AtomPostFeed, Rss2PostFeed
from organizers.feeds import AtomStartupFeed, Rss2StartupFeed

admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'
# Url configuration for new feeds
sitenews = [
    path('atom/', AtomPostFeed(), name='blogs_atom_feed'),
    path('rss/', Rss2PostFeed(), name='blogs_rss_feed'),
]
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include(blog_urls)),
    path('contact/', include(contact_urls)),
    path('startup/', include(start_urls)),
    path('tag/', include(tag_urls)),
    path('about/', TemplateView.as_view(template_name='site/about.html'), name='about_site'),
    path('mission/', TemplateView.as_view(template_name='site/mission.html'), name='site_mission'),
    path('how/', TemplateView.as_view(template_name='site/work.html'), name='site_work'),
    path('', RedirectView.as_view(
        pattern_name='blogs_posts_list',
        permanent=False
    )),
    path('users/', include(user_urls,
                           namespace='dj-auth')),
    path('sitenews/', include(sitenews)),
    path('<slug:startup_slug>/atom/', AtomStartupFeed(), name='organizers_startup_atom_feed'),
    path('<slug:startup_slug>/rss/', Rss2StartupFeed(), name='organizers_startup_rss_feed'),
    # The index view is a higher level overview of the sitemaps
    # for each section of the application.
    path('sitemap.xml', site_index_view, {'sitemaps': sitemaps_dict},
         name='sitemaps'),
    path('sitemap-<section>.xml', sitemap_view, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

suorganizer/blogs/models.py
from datetime import date
from django.db import models
from django.urls import reverse
from django.conf import settings

from organizers.models import Tag, Startup


class PostQueryset(models.QuerySet):
    """
    A custom queryset class with a
    published method.

    The reason we had to define a custom
    queryset class for post and not other
    models was because we have a method
    published. Other models don't have
    a custom method, like this.
    """

    def published(self):
        """
        A method to find all the post objects
        with pub_date from before today
        :return:
        """
        return self.filter(
            pub_date__lte=date.today()
        )


class BasePostManager(models.Manager):
    """
    Custom manager class for Post.
    """

    def get_by_natural_key(self, pub_date, slug):
        """
        Method to be used when loading data to
        database from fixtures.
        :param pub_date:
        :param slug:
        :return:
        """
        return self.get(
            pub_date=pub_date,
            slug=slug
        )


# The PostQueryset object needs to be
# linked to BasePostManager object.
# We could define get_queryset method
# in BasePostManager class or use the
# following easy approach.
PostManager = BasePostManager.from_queryset(
    PostQueryset
)


class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(
        max_length=63,
        help_text='A label for URL config',
        unique_for_month='pub_date'
    )
    text = models.TextField()
    pub_date = models.DateField(
        'Date Published',
        auto_now_add=True
    )
    tags = models.ManyToManyField(Tag,
                                  related_name='blog_posts',
                                  blank=True)
    startups = models.ManyToManyField(Startup,
                                      related_name='blog_posts',
                                      blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='blog_posts',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return 'Post {} published on {}'.format(
            self.title,
            self.pub_date.strftime('%Y-%m-%d')
        )

    def natural_key(self):
        """
        A method to return natural key tuple
        uniquely identifying the post object
        We also define dependencies that post
        has on tag and startup so they are
        serialized first.
        This method must return a tuple
        :return:
        """
        return (
            self.pub_date,
            self.slug
        )

    natural_key.dependencies = [
        'organizers.startup',
        'organizers.tag',
        'users.user'
    ]

    # we use the PostManager generated class
    # as manager for Post model.
    objects = PostManager()

    class Meta:
        verbose_name = 'blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'
        permissions = (
            ('view_future_post',
             'Can view unpublished Post'),
        )
        # Post objects are unique based on
        # slug and pub-date. While slug and
        # pk are automatically indexed, in
        # order to speed up the db queries
        # and optimise our app, we want both
        # slug and pub-date to be indexed.
        # This will do exactly that. After
        # making this change will need to
        # run the makemigration/migration command.
        # If we need to do further SQL changes
        # django offers the benefit of RUNSQL
        # in migration file, just like we used
        # RUNPYTHON
        index_together = (
            ('slug', 'pub_date'),
        )

    def get_absolute_url(self):
        return reverse('blogs_post_detail',
                       kwargs={
                           'slug': self.slug,
                           'year': self.pub_date.year,
                           'month': self.pub_date.month
                       })

    def get_update_url(self):
        return reverse('blogs_post_update',
                       kwargs={
                           'slug': self.slug,
                           'year': self.pub_date.year,
                           'month': self.pub_date.month
                       })

    def get_delete_url(self):
        return reverse('blogs_post_delete', kwargs={
            'slug': self.slug,
            'year': self.pub_date.year,
            'month': self.pub_date.month
        })

    def get_archive_year_url(self):
        return reverse(
            'blogs_post_archive_year',
            kwargs={'year': self.pub_date.year}
        )

    def get_archive_month_url(self):
        return reverse('blogs_post_archive_month',
                       kwargs={
                           'year': self.pub_date.year,
                           'month': self.pub_date.month
                       }
                       )

    def formatted_title(self):
        """
        Method to format the title
        of a post.
        Method used in setting up
        RSS feed.
        """
        return self.title.title()

    def short_text(self):
        """
        Method to return the first
        20 words of the post text.
        If the post text is less than
        20, the whole text is returned.
        Method used in setting up
        RSS feed.
        """
        if len(self.text) > 20:
            # Get the first 20 words of the text
            short = ' '.join(self.text.split()[:20])
            short += '...'
        else:
            short = self.text
        return short

suorganizer/blogs/forms.py
from django.contrib.auth import get_user
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ('author',)
        fields = '__all__'

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

    def save(self, request, commit=True):
        """
        Overriding save method to contain
        http request object so we get
        the author of the blog
        :param request:
        :param commit:
        :return:
        """
        post = super().save(commit=False)
        # if post is not already saved
        # add the current user as author
        if not post.pk:
            post.author = get_user(request)
        if commit:
            post.save()
            self.save_m2m()
        return post

suorganizer/blogs/views.py
"""
View file for blogs app
"""
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    YearArchiveView,
    MonthArchiveView,
    ArchiveIndexView,
    DetailView,
    UpdateView,
    DeleteView,

)

from .forms import PostForm
from .mixins import DateObjectMixin, AllowFuturePermissionMixin, PostFormValidMixin
from .models import Post


class PostList(
    AllowFuturePermissionMixin,
    ArchiveIndexView):
    """List View"""
    allow_empty = True
    context_object_name = 'post_list'
    date_field = 'pub_date'
    make_object_list = True
    paginate_by = 5
    model = Post
    template_name = 'post/post_list.html'


class PostDetail(LoginRequiredMixin,DateObjectMixin, DetailView):
    """Detail view"""
    template_name = 'post/post_detail.html'
    date_field = 'pub_date'
    queryset = Post.objects. \
        select_related('author__profile') \
        .prefetch_related('startups') \
        .prefetch_related('tags')


class PostCreate(LoginRequiredMixin, PostFormValidMixin, CreateView):
    """Create view"""
    form_class = PostForm
    template_name = 'post/post_form.html'
    model = Post


class PostUpdate(LoginRequiredMixin, DateObjectMixin, PostFormValidMixin, UpdateView):
    """Update view"""
    form_class = PostForm
    date_field = 'pub_date'
    model = Post
    template_name = 'post/post_form_update.html'


class PostDelete(LoginRequiredMixin, DateObjectMixin, DeleteView):
    """Delete view"""
    template_name = 'post/post_confirm_delete.html'
    success_url = reverse_lazy('blogs_posts_list')
    model = Post
    date_field = 'pub_date'


class PostArchiveYear(AllowFuturePermissionMixin, YearArchiveView):
    """View showing posts in a given year"""
    model = Post
    date_field = 'pub_date'
    template_name = 'post/post_archive_year.html'
    make_object_list = True


class PostArchiveMonth(AllowFuturePermissionMixin, MonthArchiveView):
    """View showing posts in a given month"""
    model = Post
    date_field = 'pub_date'
    template_name = 'post/post_archive_month.html'
    month_format = '%m'

suorganizer/organizers/views.py
"""
view module for organizers app
"""
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
)

from .forms import (
    TagForm,
    StartupForm,
    NewsLinkForm
)
from .mixins import (
    PageLinksMixin,
    StartupContextMixin,
    NewsLinkGetObjectMixin,
)
from .models import Tag, Startup, NewsLink


class TagList(PageLinksMixin, ListView):
    """Tag list view"""
    template_name = 'tag/tag_list.html'
    paginate_by = 5
    model = Tag


class TagDetail(DetailView):
    """Tag detail view"""
    template_name = 'tag/tag_detail.html'
    queryset = Tag.objects. \
        prefetch_related('startup_set')


class TagCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Tag create view"""
    form_class = TagForm
    template_name = 'tag/tag_form.html'
    permission_required = 'organizers.change_tag'


class TagUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Tag update view"""
    form_class = TagForm
    model = Tag
    template_name = 'tag/tag_form_update.html'
    permission_required = 'organizers.change_tag'


class TagDelete(LoginRequiredMixin, DeleteView):
    """Tag delete view"""
    template_name = 'tag/tag_confirm_delete.html'
    model = Tag
    success_url = reverse_lazy('organizers_tag_list')


class StartupList(PageLinksMixin, ListView):
    """Startup list view"""
    template_name = 'startup/startup_list.html'
    paginate_by = 5
    page_kwarg = 'page'
    model = Startup


class StartupDetail(DetailView):
    """Startup detail view"""
    template_name = 'startup/startup_detail.html'
    queryset = Startup.objects. \
        prefetch_related('tags') \
        .prefetch_related('newslink_set')


class StartupCreate(LoginRequiredMixin, CreateView):
    """Startup create view"""
    form_class = StartupForm
    template_name = 'startup/startup_form.html'


class StartupUpdate(LoginRequiredMixin, UpdateView):
    """startup update view"""
    form_class = StartupForm
    model = Startup
    template_name = 'startup/startup_form_update.html'


class StartupDelete(LoginRequiredMixin, DeleteView):
    """Startup delete view"""
    model = Startup
    template_name = 'startup/startup_confirm_delete.html'
    success_url = reverse_lazy('organizers_startup_list')


class NewsLinkCreate(LoginRequiredMixin, NewsLinkGetObjectMixin,
                     StartupContextMixin,
                     CreateView):
    """Newslink create view"""
    form_class = NewsLinkForm
    template_name = 'newslink/newslink_form.html'
    # Django by default will use get_absolute_url
    # to redirect to the newly created object detail view
    # however in our case newslink doesn't have that view
    success_url = reverse_lazy('organizers_startup_list')
    model = NewsLink

    # noinspection PyAttributeOutsideInit
    def get_initial(self):
        """
        Overriding method to add startup to
        the initial.
        Initial is then passed to the form as initial parameters
        :return:
        """
        startup_slug = self.kwargs.get(
            self.startup_slug_url_kwarg
        )
        self.startup = get_object_or_404(Startup,
                                         slug__iexact=startup_slug)
        initial = {
            self.startup_context_object_name: self.startup,
        }
        initial.update(self.initial)
        return initial


class NewsLinkUpdate(
    LoginRequiredMixin,
    StartupContextMixin,
    NewsLinkGetObjectMixin,
    UpdateView):
    """Newslink update view"""
    form_class = NewsLinkForm
    model = NewsLink
    template_name = 'newslink/newslink_form_update.html'
    # override the slug_url_kwarg so that the view knows to accept
    # newslink_slug instead of just slug
    slug_url_kwarg = 'newslink_slug'


class NewsLinkDelete(
    LoginRequiredMixin,
    StartupContextMixin,
    NewsLinkGetObjectMixin,
    DeleteView):
    """Newslink Delete view"""
    template_name = 'newslink/newslink_confirm_delete.html'
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'

    def get_success_url(self):
        """
        Redirect to the startup that the newslink was associated with,
        when the newslink is deleted.
        :return:
        """
        return (self.object.startup.
                get_absolute_url())

suorganizer/blogs/templates/post/base_blog.html
{% extends 'base.html' %} {% load static %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <section>
        {% block post_content %} This is the default content. {% endblock post_content %}
        </section>
    </div>
    <div class="col-md-4">

            <div>
                {% if perms.blogs.add_post %}
                <a class="text-info btn btn-outline-info btn-lg btn-block" href="{% url 'blogs_post_create' %}">Write New Blog</a>
                {% endif %}
            </div>
        {% block col-4 %}This is the col-4 content{% endblock col-4 %}

    </div>
</div>
<div class="row">
    <div class="col">
        {% block pagination %}{% endblock pagination %}
    </div>
</div>
{% endblock content %}

suorganizer/blogs/templates/post/post_archive_month.html
{% extends 'post/base_blog.html' %}
{% block title %}
{{ block.super }} - {{ month|date:'F Y' }} Posts
{% endblock %}
{% load blog_latest %}
{% block post_content %}
        <h2>All Posts for {{ month|date:'F Y'}}</h2>
        {% for post in post_list %}
        <article>
            <header>
                <div class="card text-white bg-transparent border-dark">
                        <div class="card-header">
                            <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
                            </h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                Written on: {{ post.pub_date|date:"l, Fj, Y"}}
                            </p>
                            <p>{{ post.text|truncatewords:20 }}</p>
                            <a href="{{ post.get_absolute_url }}">Read more&hellip;</a>
                        </div>
                </div>
                <div class="d-flex justify-content-start">
                    {% if perms.blogs.change_post %}
                    <p>
                        <a class="text-warning" href="{{ post.get_update_url }}" title="Edit"><span
                                class="material-icons">edit</span></a>
                    </p>
                    {% endif %}
                    {% if perms.blogs.delete_post %}
                    <p>
                        <a class="text-danger" href="{{ post.get_delete_url }}" title="Delete"><span
                                class="material-icons">delete_forever</span></a>
                    </p>
                    {% endif %}
                </div>

            </header>
        </article>
        {% endfor %}
    {% endblock post_content %}
    {% block col-4 %}
        <section class="latest_post">
        <p>
            <a href="{% url 'blogs_post_archive_year' month|date:'Y' %}">All Posts from {{ month|date:'Y' }}</a>
        </p>
        </section>
        {% get_latest_posts 5 %}
         <section class="latest_post">
             <h4>Latest Posts </h4>
                 {% for latest_post in latest_post_list %}
            <p>
            <a href="{{ latest_post.get_absolute_url }}">
                {{ latest_post.title }}
            </a>
            </p>
            {% endfor %}
         </section>
    {% endblock col-4 %}
    {% block pagination %}
        <nav aria-label="Page navigation example" class="pagination_nav">
            <ul class="pagination">
                {% if previous_month %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'blogs_post_archive_month' previous_month|date:'Y' previous_month|date:'m' %}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo; Previous</span>
                    </a>
                </li>
                {% endif %}
                {% if next_month %}
            <li class="page-item">
      <a class="page-link" href="{% url 'blogs_post_archive_month' next_month|date:'Y' next_month|date:'m' %}"
         aria-label="Next">
        <span aria-hidden="true">Next &raquo;</span>
      </a>
    </li>
            {% endif %}
        </ul>
        </nav>
    {% endblock pagination %}

suorganizer/blogs/templates/post/post_archive_year.html
{% extends 'post/base_blog.html' %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - {{ year|date:'Y' }} Posts
{% endblock %}
{% load blog_latest %}
{% block post_content %}
        <h2>All Posts for {{ year|date:'Y' }}</h2>
        {% for post in post_list %}
        <article>
            <header>
                <div class="card text-white bg-transparent border-dark">
                        <div class="card-header">
                            <h5 class="card-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
                            </h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                Written on: {{ post.pub_date|date:"l, Fj, Y"}}
                            </p>
                            <p>{{ post.text|truncatewords:20 }}</p>
                            <a href="{{ post.get_absolute_url }}">Read more&hellip;</a>
                        </div>
                </div>
                <div class="d-flex justify-content-start">
                    {% if perms.blogs.change_post %}
                    <p>
                        <a class="text-warning" href="{{ post.get_update_url }}" title="Edit">
                            <span class="material-icons">edit</span>
                        </a>
                    </p>
                    {% endif %}
                    {% if perms.blogs.delete_post %}
                    <p>
                        <a class="text-danger" href="{{ post.get_delete_url }}" title="Delete">
                            <span class="material-icons">delete_forever</span>
                        </a>
                    </p>
                    {% endif %}
                </div>
            </header>
        </article>
        {% endfor %}
        {% endblock post_content %}
        {% block col-4 %}
        <section class="latest_post">
            <h3>Archive by Month</h3>
                <ul>
                    {% for month in date_list %}
                    <li>
                        <a href="{% url 'blogs_post_archive_month' month|date:'Y' month|date:'n' %}">{{ month|date:"F Y" }}</a>
                    </li>
                    {% endfor %}
                </ul>
        </section>
        {% get_latest_posts 5 %}
         <section class="latest_post">
             <h4>Latest Posts </h4>
                 {% for latest_post in latest_post_list %}
            <p>
            <a href="{{ latest_post.get_absolute_url }}">
                {{ latest_post.title }}
            </a>
            </p>
            {% endfor %}
         </section>
        {% endblock col-4 %}
        {% block pagination %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
            {% if previous_year %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'blogs_post_archive_year' previous_year|date:'Y' %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            {% endif %}
            {% if next_year %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'blogs_post_archive_year' next_year|date:'Y' %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            {% endif %}
            </ul>
        </nav>
        {% endblock pagination %}

suorganizer/blogs/templates/post/post_confirm_delete.html
{% extends 'post/base_blog.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Delete Blog Post
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% delete_form  post.get_delete_url 'Delete Blog Post' post %}
    </div>
    <div class="col-md-4">
    <p>
        <a href="{{ request.META.HTTP_REFERER}}">Go Back</a>
    </p>
        </div>
</div>
{% endblock %}

suorganizer/blogs/templates/post/post_detail.html
{% extends 'post/base_blog.html' %}
{% block title %}
{{ block.super }} - {{ post.title|title }}
{% endblock %}
{% block content %}
<article>
    <header>
        <h2 class="text-center text-info">{{ post.title|title }}</h2>
        <div class="d-flex justify-content-between">
            <p class="text-left font-weight-light text-success written_on">
                Written on:
            </p>
            <p class="text-right text-success font-weight-light">
                <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                    {{ post.pub_date|date:"l, F j, Y" }}
                </time>
            </p>
        </div>

    </header>
    <div>
        <p class="body_text font-weight-light">
            {{ post.text|linebreaks }}
        </p>
    </div>
    <div class="d-flex justify-content-start">
        {% if perms.blogs.change_post %}
        <p>
            <a class="text-warning" href="{{ post.get_update_url }}" title="Edit"><span
                    class="material-icons">edit</span></a>
        </p>
        {% endif %}
        {% if perms.blogs.delete_post %}
        <p>
            <a class="text-danger" href="{{ post.get_delete_url }}" title="Delete"><span class="material-icons">delete_forever</span></a>
        </p>
        {% endif %}
    </div>
    {% if post.startups.all or post.tags.all %}
    <footer>
        {% if post.startups.all %}
        <section>
            <h3>Startup{{ post.startups.all|pluralize }}</h3>
            <ul>
                {% for startup in post.startups.all %}
                <li>
                    <a href="{{ startup.get_absolute_url }}">
                        {{ startup.name }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
        {% endif %}
        {% if post.tags.all %}
        <section>
            <h3>Tag{{ post.tags.all|pluralize }}</h3>
            <ul>
                {% for tag in post.tags.all %}
                <li>
                    <a href="{{ tag.get_absolute_url }}">
                        {{ tag.name|title }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
        {% endif %}
    </footer>
    {% endif %}
</article>
<br>
<p>
    <a href="{{ request.META.HTTP_REFERER}}">Go Back</a>
</p>
{% endblock %}

suorganizer/blogs/templates/post/post_form.html
{% extends 'post/base_blog.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Create Blog Post
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% url 'blogs_post_create' as form_url %}
        {% form form_url 'Create Blog Post' 'post' button_classes='btn btn-outline-success btn-lg btn-block' %}
        </div>
    </div>
{% endblock %}

suorganizer/blogs/templates/post/post_form_update.html
{% extends 'post/base_blog.html' %}
{% load display_form %}
{% block title %}
{{ block.super }} - Update Blog Post
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% form post.get_update_url 'Update Blog Post' 'post' button_classes='btn btn-outline-warning btn-lg btn-block' %}
    </div>
    <div class="col-md-4">
    <p>
        <a href="{{ request.META.HTTP_REFERER}}">Go Back</a>
    </p>
        </div>
</div>
{% endblock %}

suorganizer/blogs/templates/post/post_list.html
{% extends 'post/base_blog.html' %} {% block title %} {{ block.super }} - Blog List {% endblock %}
{% block post_content %}
            {% for post in post_list %}
            <article>
                <header>
                    <div class="card text-white bg-transparent border-dark">
                        <div class="card-header">
                            <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
                            </h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                Written on: {{ post.pub_date|date:"l, Fj, Y"}}
                            </p>
                            <p>{{ post.text|truncatewords:20 }}</p>
                            <a href="{{ post.get_absolute_url }}">Read more&hellip;</a>
                        </div>
                    </div>
                        <div class="d-flex justify-content-start">
                            {% if perms.blogs.change_post %}
                            <p>
                                <a class="text-warning" href="{{ post.get_update_url }}" title="Edit"><span
                                        class="material-icons">edit</span></a>
                            </p>
                            {% endif %}
                            {% if perms.blogs.delete_post %}
                            <p>
                                <a class="text-danger" href="{{ post.get_delete_url }}" title="Delete"><span
                                        class="material-icons">delete_forever</span></a>
                            </p>
                            {% endif %}
                        </div>
                </header>
            </article>
            {% empty %}
            <p><em>No Blog Posts Available</em></p>
            {% endfor %}
        {% endblock post_content %}
        {% block col-4 %}
        <section class="latest_post">
            <h3>Post Archives</h3>
            <ul>
                {% for y in date_list %}
                <li><a href="{% url 'blogs_post_archive_year' y|date:'Y' %}">
                    {{ y|date:"Y" }}
                </a></li>
                {% endfor %}
            </ul>
        </section>
        {% endblock col-4 %}
        {% block pagination %}
        {% endblock pagination %}