suorganizer/blogs/urls.py
from django.urls import path
from .views import (
    PostList,
    PostDetail,
    PostCreate,
    PostUpdate,
    PostDelete,
    PostArchiveYear,
    PostArchiveMonth,
)

urlpatterns = [
    path('', PostList.as_view(), name='blogs_posts_list'),
    path('<int:year>/<int:month>/<slug:slug>/', PostDetail.as_view(), name='blogs_post_detail'),
    path('create/', PostCreate.as_view(), name='blogs_post_create'),
    path('<int:year>/<int:month>/<slug:slug>/update/', PostUpdate.as_view(), name='blogs_post_update'),
    path('<int:year>/<int:month>/<slug:slug>/delete/', PostDelete.as_view(), name='blogs_post_delete'),
    path('<int:year>/', PostArchiveYear.as_view(), name='blogs_post_archive_year'),
    path('<int:year>/<int:month>/', PostArchiveMonth.as_view(), name='blogs_post_archive_month'),
]

suorganizer/suorganizer/urls.py
import os
from blogs import urls as blog_urls
from contacts import urls as contact_urls
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view
)

from .sitemaps import sitemaps as sitemaps_dict
from organizers.urls import startup as start_urls
from organizers.urls import tag as tag_urls
from users import urls as user_urls
from blogs.feeds import AtomPostFeed, Rss2PostFeed
from organizers.feeds import AtomStartupFeed, Rss2StartupFeed

admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'
# Url configuration for new feeds
sitenews = [
    path('atom/', AtomPostFeed(), name='blogs_atom_feed'),
    path('rss/', Rss2PostFeed(), name='blogs_rss_feed'),
]
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include(blog_urls)),
    path('contact/', include(contact_urls)),
    path('startup/', include(start_urls)),
    path('tag/', include(tag_urls)),
    path('about/', TemplateView.as_view(template_name='site/about.html'), name='about_site'),
    path('mission/', TemplateView.as_view(template_name='site/mission.html'), name='site_mission'),
    path('how/', TemplateView.as_view(template_name='site/work.html'), name='site_work'),
    path('', RedirectView.as_view(
        pattern_name='blogs_posts_list',
        permanent=False
    )),
    path('users/', include(user_urls,
                           namespace='dj-auth')),
    path('sitenews/', include(sitenews)),
    path('<slug:startup_slug>/atom/', AtomStartupFeed(), name='organizers_startup_atom_feed'),
    path('<slug:startup_slug>/rss/', Rss2StartupFeed(), name='organizers_startup_rss_feed'),
    # The index view is a higher level overview of the sitemaps
    # for each section of the application.
    path('sitemap.xml', site_index_view, {'sitemaps': sitemaps_dict},
         name='sitemaps'),
    path('sitemap-<section>.xml', sitemap_view, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

suorganizer/users/urls.py
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

from .views import (DisableAccount, CreateAccount,
                    ActivateAccount, ResendActivationEmail,
                    ProfileDetail, ProfileUpdate, PublicProfileDetail)

app_name = 'dj-auth'

password_url = [
    # We are adding this pattern to ensure that
    # /user/password/ pattern is resolved.
    # This is good practice.
    path('',
         RedirectView.as_view(
             pattern_name='dj-auth:pw_reset_start',
             permanent=False
         )),
    path('change/',
         auth_views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url=reverse_lazy('dj-auth:pw_change_done')
         ), name='pw_change'),
    path('change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'
         ), name='pw_change_done'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.txt',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('dj-auth:pw_reset_sent')
    ), name='pw_reset_start'),
    path('reset/sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_sent.html'
    ), name='pw_reset_sent'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('dj-auth:pw_reset_complete')
    ), name='pw_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',
        extra_context={'form': 'AuthenticationForm'}
    ), name='pw_reset_complete')

]

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'
    )
         , name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logged_out.html',
        extra_context={
            'form': AuthenticationForm

        }
    )
         , name='logout'),
    path('password/', include(password_url)),
    path('disable/', DisableAccount.as_view(), name='disable'),
    path('create/', CreateAccount.as_view(), name='create'),
    path('create/done/', TemplateView.as_view(
        template_name='users/user_create_done.html'),
         name='create_done'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(),
         name='activate'),
    path('activate/resend/', ResendActivationEmail.as_view(),
         name='resend_activation'),
    path('profile/',
         ProfileDetail.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdate.as_view(),
         name='profile_update'),
    path('<slug:slug>/', PublicProfileDetail.as_view(),
         name='public_profile'),
    # Just like the above we have to add this path
    # as currently /user/activate/ doesn't resolve
    path('activate/',
         RedirectView.as_view(
             pattern_name=(
                 'dj-auth:resend_activation'
             ),
             permanent=False
         )),
    path('', RedirectView.as_view(
        pattern_name='dj-auth:login',
        permanent=False
    ), ),
]

suorganizer/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} Startup Organizer {% endblock title %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="alternate" title="Blogs News RSS" type="application/rss+xml"
          href="{% url 'blogs_rss_feed' %}">
    <link rel="alternate" title="Blogs News Atom" type="application/atom+xml"
          href="{% url 'blogs_atom_feed' %}">
</head>

<body>
<header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blogs_posts_list' %}">SUORGANIZER</a>
                <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                        class="navbar-toggler" data-target="#navbarSupportedContent"
                        data-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a href="{% url 'blogs_posts_list' %}" class="nav-link">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'organizers_startup_list' %}">Startups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'organizers_tag_list' %}">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'contact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sitemaps' %}">Sitemap</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About US
                                </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'about_site' %}">About Us</a>
                                <a class="dropdown-item" href="{% url 'site_mission' %}">Our Mission</a>
                                <a class="dropdown-item" href="{% url 'site_work' %}">What we do</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            User
                                </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'dj-auth:logout' %}?next={{ request.path }}">Log Out</a>
                                <a class="dropdown-item" href="{% url 'dj-auth:profile' %}">View Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'dj-auth:profile_update' %}">Update Profile</a>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'dj-auth:login' %}?next={{ request.path }}">Log In</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </div>
</header>
<main>
    <div class="container">
        {% if messages %}
        <div>
            <div>

                {% for message in messages %} {% if message.tags %}
                <div class="alert alert-{{message.tags }} text-center text-capitalize" role="alert">
                    {{ message }}
                </div>
                {% else %}
                <div>
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}

            </div>
        </div>
        {% endif %}
        {% block content %} This is the default content. {% endblock content %}

    </div>
</main>
<br>
<footer>
    <div class="container">
        <hr>

        <div class="row justify-content-md-between">
            <div class="col-md-3">
                <p class="font-weight-light text-justify">
                    &copy;2020
                    <a href="https://AndresForge.com">
                        Mohammad Ayub
                    </a>
                </p>
            </div>
            <div class="col-md-2">
                <p class="font-weight-light text-justify">SUORGANIZER</p>
            </div>
            <div class="col-md-3">
                <p class="font-weight-light text-justify">
                    Created for
                    <a href="https://Django-Unleashed.com/">
                        Devteams Inc
                    </a>
                </p>
            </div>
            <div class="col-md-2">
                <a href="{% url 'blogs_rss_feed' %}">Blogs RSS Feed</a>
            </div>
            <div class="col-md-2">
                <a href="{% url 'blogs_atom_feed' %}">Blogs Atom Feed</a>
            </div>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>

</html>